### PR TITLE
SOFTWARE-6027: Add osg 24 to build matrix

### PR DESCRIPTION
**Pull request by mwestphall**

### CODE REVIEW

**Review by brianhlin — APPROVED** [review]
LGTM

**Comment by matyasselmeci** [comment]
Does this have external users? Maybe once we are satisfied that OSG 24-based builds work, we can remove OSG 23 from the build matrix.

**Comment by mwestphall** [comment]
I believe it's all internal, Also, the 23-* build series has never been used in prod, all the PATh facilities are currently still on a 3.6 build

**Comment by brianhlin** [comment]
Good point. I'm down with removing the 23-* build series outright

**Pull request merged**
