### PR TITLE
Add build-sw-container workflow, etc (SOFTWARE-5206)

### PR DESCRIPTION
**Pull request by edquist**
Note the workflow is just the default one in opensciencegrid Actions, per https://osg-htc.org/technology/software/container-development-guide/index.html#old-image-repositories

### CODE REVIEW

**Comment by brianhlin** [comment]
Oh hey, our internal docs are out of date. Could you use our push container action instead? https://github.com/opensciencegrid/osgvo-docker-pilot/blob/master/.github/workflows/build-container.yml#L65-L91

**Comment by edquist** [comment]
Ok @brianhlin how is this? ([152d8e8](https://github.com/opensciencegrid/htcondor-autoscale-manager/pull/1/commits/152d8e8d79552749d45e778c469161a336452591))

**Comment by edquist** [comment]
also note for potential future use: the one you mentioned [above](https://github.com/opensciencegrid/osgvo-docker-pilot/blob/master/.github/workflows/build-container.yml#L65-L91) references the `master` branch where this repo calls it `main`

**Review by brianhlin — APPROVED** [review]
LGTM!

**Pull request merged**
